#pragma once

#ifndef _TOOL_ENUM_H_
#define _TOOL_ENUM_H_

typedef enum eGameObjectTag
{
	OBJECT_TAG_DEFAULT,
	OBJECT_TAG_TERRAIN,
	OBJECT_TAG_MAINCAM,
	OBJECT_TAG_PLAYER,
	OJBECT_TAG_UI,
	OBJECT_TAG_END
}OBJECT_TAG;

#endif //_TOOL_ENUM_H_